/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1682964203504066080L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserV2\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favoriteNumber\",\"type\":[\"int\",\"null\"]},{\"name\":\"favoriteColor\",\"type\":[\"string\",\"null\"]},{\"name\":\"sex\",\"type\":{\"type\":\"enum\",\"name\":\"Sex\",\"symbols\":[\"male\",\"female\",\"third\"]}},{\"name\":\"favoriteMovie\",\"type\":[\"string\",\"null\"],\"default\":\"007\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserV2> ENCODER =
      new BinaryMessageEncoder<UserV2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserV2> DECODER =
      new BinaryMessageDecoder<UserV2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserV2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserV2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserV2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserV2>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserV2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserV2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserV2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserV2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.Integer favoriteNumber;
  private java.lang.CharSequence favoriteColor;
  private example.avro.Sex sex;
  private java.lang.CharSequence favoriteMovie;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserV2() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param favoriteNumber The new value for favoriteNumber
   * @param favoriteColor The new value for favoriteColor
   * @param sex The new value for sex
   * @param favoriteMovie The new value for favoriteMovie
   */
  public UserV2(java.lang.CharSequence name, java.lang.Integer favoriteNumber, java.lang.CharSequence favoriteColor, example.avro.Sex sex, java.lang.CharSequence favoriteMovie) {
    this.name = name;
    this.favoriteNumber = favoriteNumber;
    this.favoriteColor = favoriteColor;
    this.sex = sex;
    this.favoriteMovie = favoriteMovie;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return favoriteNumber;
    case 2: return favoriteColor;
    case 3: return sex;
    case 4: return favoriteMovie;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: favoriteNumber = (java.lang.Integer)value$; break;
    case 2: favoriteColor = (java.lang.CharSequence)value$; break;
    case 3: sex = (example.avro.Sex)value$; break;
    case 4: favoriteMovie = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'favoriteNumber' field.
   * @return The value of the 'favoriteNumber' field.
   */
  public java.lang.Integer getFavoriteNumber() {
    return favoriteNumber;
  }


  /**
   * Sets the value of the 'favoriteNumber' field.
   * @param value the value to set.
   */
  public void setFavoriteNumber(java.lang.Integer value) {
    this.favoriteNumber = value;
  }

  /**
   * Gets the value of the 'favoriteColor' field.
   * @return The value of the 'favoriteColor' field.
   */
  public java.lang.CharSequence getFavoriteColor() {
    return favoriteColor;
  }


  /**
   * Sets the value of the 'favoriteColor' field.
   * @param value the value to set.
   */
  public void setFavoriteColor(java.lang.CharSequence value) {
    this.favoriteColor = value;
  }

  /**
   * Gets the value of the 'sex' field.
   * @return The value of the 'sex' field.
   */
  public example.avro.Sex getSex() {
    return sex;
  }


  /**
   * Sets the value of the 'sex' field.
   * @param value the value to set.
   */
  public void setSex(example.avro.Sex value) {
    this.sex = value;
  }

  /**
   * Gets the value of the 'favoriteMovie' field.
   * @return The value of the 'favoriteMovie' field.
   */
  public java.lang.CharSequence getFavoriteMovie() {
    return favoriteMovie;
  }


  /**
   * Sets the value of the 'favoriteMovie' field.
   * @param value the value to set.
   */
  public void setFavoriteMovie(java.lang.CharSequence value) {
    this.favoriteMovie = value;
  }

  /**
   * Creates a new UserV2 RecordBuilder.
   * @return A new UserV2 RecordBuilder
   */
  public static example.avro.UserV2.Builder newBuilder() {
    return new example.avro.UserV2.Builder();
  }

  /**
   * Creates a new UserV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserV2 RecordBuilder
   */
  public static example.avro.UserV2.Builder newBuilder(example.avro.UserV2.Builder other) {
    if (other == null) {
      return new example.avro.UserV2.Builder();
    } else {
      return new example.avro.UserV2.Builder(other);
    }
  }

  /**
   * Creates a new UserV2 RecordBuilder by copying an existing UserV2 instance.
   * @param other The existing instance to copy.
   * @return A new UserV2 RecordBuilder
   */
  public static example.avro.UserV2.Builder newBuilder(example.avro.UserV2 other) {
    if (other == null) {
      return new example.avro.UserV2.Builder();
    } else {
      return new example.avro.UserV2.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserV2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserV2>
    implements org.apache.avro.data.RecordBuilder<UserV2> {

    private java.lang.CharSequence name;
    private java.lang.Integer favoriteNumber;
    private java.lang.CharSequence favoriteColor;
    private example.avro.Sex sex;
    private java.lang.CharSequence favoriteMovie;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.UserV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.favoriteNumber)) {
        this.favoriteNumber = data().deepCopy(fields()[1].schema(), other.favoriteNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.favoriteColor)) {
        this.favoriteColor = data().deepCopy(fields()[2].schema(), other.favoriteColor);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sex)) {
        this.sex = data().deepCopy(fields()[3].schema(), other.sex);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.favoriteMovie)) {
        this.favoriteMovie = data().deepCopy(fields()[4].schema(), other.favoriteMovie);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing UserV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.UserV2 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favoriteNumber)) {
        this.favoriteNumber = data().deepCopy(fields()[1].schema(), other.favoriteNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favoriteColor)) {
        this.favoriteColor = data().deepCopy(fields()[2].schema(), other.favoriteColor);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sex)) {
        this.sex = data().deepCopy(fields()[3].schema(), other.sex);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.favoriteMovie)) {
        this.favoriteMovie = data().deepCopy(fields()[4].schema(), other.favoriteMovie);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public example.avro.UserV2.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public example.avro.UserV2.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'favoriteNumber' field.
      * @return The value.
      */
    public java.lang.Integer getFavoriteNumber() {
      return favoriteNumber;
    }


    /**
      * Sets the value of the 'favoriteNumber' field.
      * @param value The value of 'favoriteNumber'.
      * @return This builder.
      */
    public example.avro.UserV2.Builder setFavoriteNumber(java.lang.Integer value) {
      validate(fields()[1], value);
      this.favoriteNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'favoriteNumber' field has been set.
      * @return True if the 'favoriteNumber' field has been set, false otherwise.
      */
    public boolean hasFavoriteNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'favoriteNumber' field.
      * @return This builder.
      */
    public example.avro.UserV2.Builder clearFavoriteNumber() {
      favoriteNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'favoriteColor' field.
      * @return The value.
      */
    public java.lang.CharSequence getFavoriteColor() {
      return favoriteColor;
    }


    /**
      * Sets the value of the 'favoriteColor' field.
      * @param value The value of 'favoriteColor'.
      * @return This builder.
      */
    public example.avro.UserV2.Builder setFavoriteColor(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.favoriteColor = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'favoriteColor' field has been set.
      * @return True if the 'favoriteColor' field has been set, false otherwise.
      */
    public boolean hasFavoriteColor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'favoriteColor' field.
      * @return This builder.
      */
    public example.avro.UserV2.Builder clearFavoriteColor() {
      favoriteColor = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sex' field.
      * @return The value.
      */
    public example.avro.Sex getSex() {
      return sex;
    }


    /**
      * Sets the value of the 'sex' field.
      * @param value The value of 'sex'.
      * @return This builder.
      */
    public example.avro.UserV2.Builder setSex(example.avro.Sex value) {
      validate(fields()[3], value);
      this.sex = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sex' field has been set.
      * @return True if the 'sex' field has been set, false otherwise.
      */
    public boolean hasSex() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sex' field.
      * @return This builder.
      */
    public example.avro.UserV2.Builder clearSex() {
      sex = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'favoriteMovie' field.
      * @return The value.
      */
    public java.lang.CharSequence getFavoriteMovie() {
      return favoriteMovie;
    }


    /**
      * Sets the value of the 'favoriteMovie' field.
      * @param value The value of 'favoriteMovie'.
      * @return This builder.
      */
    public example.avro.UserV2.Builder setFavoriteMovie(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.favoriteMovie = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'favoriteMovie' field has been set.
      * @return True if the 'favoriteMovie' field has been set, false otherwise.
      */
    public boolean hasFavoriteMovie() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'favoriteMovie' field.
      * @return This builder.
      */
    public example.avro.UserV2.Builder clearFavoriteMovie() {
      favoriteMovie = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserV2 build() {
      try {
        UserV2 record = new UserV2();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.favoriteNumber = fieldSetFlags()[1] ? this.favoriteNumber : (java.lang.Integer) defaultValue(fields()[1]);
        record.favoriteColor = fieldSetFlags()[2] ? this.favoriteColor : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sex = fieldSetFlags()[3] ? this.sex : (example.avro.Sex) defaultValue(fields()[3]);
        record.favoriteMovie = fieldSetFlags()[4] ? this.favoriteMovie : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserV2>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserV2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserV2>
    READER$ = (org.apache.avro.io.DatumReader<UserV2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    if (this.favoriteNumber == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.favoriteNumber);
    }

    if (this.favoriteColor == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.favoriteColor);
    }

    out.writeEnum(this.sex.ordinal());

    if (this.favoriteMovie == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.favoriteMovie);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.favoriteNumber = null;
      } else {
        this.favoriteNumber = in.readInt();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.favoriteColor = null;
      } else {
        this.favoriteColor = in.readString(this.favoriteColor instanceof Utf8 ? (Utf8)this.favoriteColor : null);
      }

      this.sex = example.avro.Sex.values()[in.readEnum()];

      if (in.readIndex() != 0) {
        in.readNull();
        this.favoriteMovie = null;
      } else {
        this.favoriteMovie = in.readString(this.favoriteMovie instanceof Utf8 ? (Utf8)this.favoriteMovie : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.favoriteNumber = null;
          } else {
            this.favoriteNumber = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.favoriteColor = null;
          } else {
            this.favoriteColor = in.readString(this.favoriteColor instanceof Utf8 ? (Utf8)this.favoriteColor : null);
          }
          break;

        case 3:
          this.sex = example.avro.Sex.values()[in.readEnum()];
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.favoriteMovie = null;
          } else {
            this.favoriteMovie = in.readString(this.favoriteMovie instanceof Utf8 ? (Utf8)this.favoriteMovie : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










