version: '3.3'
services:
  mysql-master:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db1
    links:
      - mysql-slave
    ports:
      - 33065:3306
    volumes:
      - ./master-my.cnf:/etc/my.cnf
      - /home/myname/bin/mysql-8.0.27-linux-glibc2.17-x86_64-minimal:/mybin
  mysql-slave:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db1
    ports:
      - 33066:3306
    volumes:
      - ./slave-my.cnf:/etc/my.cnf
