spring:
  cloud:
    stream:
      schema:
        avro:
          dynamicSchemaGenerationEnabled: true
      default:
        producer:
          useNativeEncoding: false
      bindings:
        output:
          destination: user-details
          content-type: application/*+avro
